### ISSUE TITLE
All fields should be nullable

### ISSUE THREAD

**Issue by silkentrance** [matthiask/feincms3-meta#1]
All fields introduced by the MetaMixin must be nullable.

The reasoning here is that a None (NULL) is equivalent to a blank string `''` in that

```
s = None

if not s:
  print('not s')

s = ''

if not s:
  print('not s')
```

is equivalent.

For the purpose of this app we do not need any equivalency checks, e.g. ``None == ''``, therefore we can 
safely assume that  None and the empty string are equivalent.

In turn, this will leverage the need for (test) fixtures to not having to provide blank string data for otherwise unused fields.

A PR for this will be provided, see #2.

**Comment by matthiask** [comment]
Here's a pattern we often use:

app/pages/utils.py:

```python
from django.conf import settings
from feincms3.applications import page_for_app_request
from feincms3_meta.utils import meta_tags

from app.pages.renderer import renderer
from app.regions import BaseRegions


def page_context(request, *, page=None):
    page = page or page_for_app_request(request)
    page.activate_language(request)
    ancestors = list(page.ancestors().reverse())
    return {
        "page": page,
        "page_regions": BaseRegions.from_item(
            page,
            renderer=renderer,
            inherit_from=ancestors,
            timeout=0 if settings.DEBUG else 30,
        ),
        "meta_tags": meta_tags([page] + ancestors, request=request),
    }
```

app/pages/views.py:
```python
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from app.pages.models import Page
from app.pages.utils import page_context


def page_detail(request, path=None):
    page = get_object_or_404(
        Page.objects.active(), path="/{}/".format(path) if path else "/"
    )

    if page.redirect_to_url:
        return HttpResponseRedirect(page.redirect_to_url)
    elif page.redirect_to_page:
        return HttpResponseRedirect(page.redirect_to_page)

    return render(request, page.type.template_name, page_context(request, page=page))
```

The list of objects passed as ``inherit_from`` to ``Regions.from_item`` and ``meta_tags`` can be read as a list of fallback objects. Values which aren't provided by earlier objects are taken from later objects.

I can see that this may be confusing or misleading if you think of a regular assignment where later values override the former.

Since we have many sites using this pattern I'd be unhappy if the API were changed. Maybe we could change the docs or extend the parameters of the function to accomodate other behaviors? I'm not sure.
